### ISSUE TITLE
MinVariance

### ISSUE THREAD

**Issue by trh0ly** [tschm/MosekRegression#1]
Using `weights = model.variable("weights", matrix.shape[1], Domain.inRange(0.0, +np.infty))` @line 123 in solver.py raises "Error: rescode.err_upper_bound_is_a_nan(1391): The upper bound specified is not a number (nan)."

Using "model.variable("weights", matrix.shape[1], Domain.inRange(0.0, 1.0))" instead should solve that problem?

**Comment by tschm** [comment]
interesting, thank you for the fix
