### ISSUE TITLE
Predictor

### ISSUE THREAD

**Issue by trh0ly** [tschm/MosekRegression#2]
Using `t = model.variable(name, expr.size(), Domain.unbounded())` @line 23 in solver.py raises "AttributeError: 'LinearVariable' object has no attribute 'size'"

Same for `for i in range(0, int(expr.size())):` @line 26

Using `t = model.variable(name, expr.getShape(), Domain.unbounded())` and `for i in range(0, int(expr.getShape())):` instead should solve that problem.

**Comment by tschm** [comment]
Thank you. getShape is a terrible choice for a name in Python
